namespace Northpass.ViewModels;

public sealed class UiStrings(string language)
{
    public string this[string key]
    {
        get
        {
            if (!Entries.TryGetValue(key, out var text)) return key;
            return language switch { "ru" => text.Ru, "az" => text.Az, _ => text.En };
        }
    }
    private static readonly Dictionary<string, (string En, string Ru, string Az)> Entries = new()
    {
        ["EngineSetup"] = ("Components", "Компоненты", "Komponentlər"),
        ["SetupRequired"] = ("Preparing components", "Подготовка компонентов", "Komponentlər hazırlanır"),
        ["Downloading"] = ("Preparing components", "Подготовка компонентов", "Komponentlər hazırlanır"),
        ["Verifying"] = ("Checking components", "Проверка компонентов", "Komponentlər yoxlanılır"),
        ["Extracting"] = ("Preparing components", "Подготовка компонентов", "Komponentlər hazırlanır"),
        ["Ready"] = ("Ready", "Готово", "Hazır"),
        ["SetupFailed"] = ("Installation needs attention", "Требуется восстановление", "Quraşdırma diqqət tələb edir"),
        ["SetupEngine"] = ("Try again", "Повторить", "Yenidən cəhd et"),
        ["RepairEngine"] = ("Repair installation", "Восстановить установку", "Quraşdırmanı bərpa et"),
        ["EngineRepairConsent"] = ("Restore the components included with Northpass? Your preferences will be kept. If Windows is still using a component, you may need to restart your computer.", "Восстановить компоненты, поставляемые с Northpass? Ваши настройки сохранятся. Если Windows использует компонент, может потребоваться перезагрузка компьютера.", "Northpass ilə gələn komponentlər bərpa edilsin? Parametrləriniz saxlanılacaq. Windows komponentdən istifadə edirsə, kompüteri yenidən başlatmaq lazım ola bilər."),
        ["UpdateEngine"] = ("Update components", "Обновить компоненты", "Komponentləri yenilə"),
        ["RollbackEngine"] = ("Restore previous version", "Вернуть предыдущую версию", "Əvvəlki versiyanı bərpa et"),
        ["EngineConsent"] = ("Northpass prepares its included components automatically.", "Northpass автоматически подготавливает встроенные компоненты.", "Northpass daxil edilmiş komponentləri avtomatik hazırlayır."),
        ["EngineUpdateConsent"] = ("Apply the components included with this Northpass update? The previous version will be kept for recovery.", "Установить компоненты этого обновления Northpass? Предыдущая версия сохранится для восстановления.", "Bu Northpass yeniləməsinə daxil olan komponentlər tətbiq edilsin? Əvvəlki versiya bərpa üçün saxlanılacaq."),
        ["EngineRollbackConsent"] = ("Restore the previous component version? Northpass will check it before use.", "Вернуть предыдущую версию компонентов? Northpass проверит её перед использованием.", "Əvvəlki komponent versiyası bərpa edilsin? Northpass istifadə etməzdən əvvəl onu yoxlayacaq."),
        ["Dashboard"] = ("Home", "Главная", "Əsas"),
        ["Strategies"] = ("Advanced", "Дополнительно", "Əlavə"),
        ["Diagnostics"] = ("Diagnostics", "Диагностика", "Diaqnostika"),
        ["Settings"] = ("Settings", "Настройки", "Parametrlər"),
        ["About"] = ("About", "О программе", "Haqqında"),
        ["Connect"] = ("Connect", "Подключиться", "Qoşul"),
        ["Disconnect"] = ("Disconnect", "Отключиться", "Ayrıl"),
        ["Disconnected"] = ("Disconnected", "Отключено", "Ayrılıb"),
        ["Connecting"] = ("Connecting", "Подключение", "Qoşulur"),
        ["Active"] = ("Connection started", "Соединение запущено", "Bağlantı başladılıb"),
        ["Stopping"] = ("Disconnecting", "Отключение", "Ayrılır"),
        ["Error"] = ("Connection needs attention", "Требуется проверка соединения", "Bağlantı diqqət tələb edir"),
        ["Strategy"] = ("Current strategy", "Текущая стратегия", "Cari strategiya"),
        ["Session"] = ("Session duration", "Длительность сессии", "Sessiya müddəti"),
        ["Unverified"] = ("Not tested", "Не проверена", "Yoxlanılmayıb"),
        ["Validate"] = ("Validate configuration", "Проверить конфигурацию", "Konfiqurasiyanı yoxla"),
        ["Import"] = ("Import", "Импорт", "İdxal"),
        ["Export"] = ("Export", "Экспорт", "İxrac"),
        ["Refresh"] = ("Refresh", "Обновить", "Yenilə"),
        ["ExportLogs"] = ("Export logs", "Экспорт журнала", "Jurnalı ixrac et"),
        ["ClearLogs"] = ("Clear logs", "Очистить журнал", "Jurnalı təmizlə"),
        ["Initializing"] = ("Initializing", "Запускаем Northpass", "Northpass başladılır"),
        ["LoadingInterface"] = ("Loading interface", "Загружаем интерфейс", "İnterfeys yüklənir"),
        ["CurrentSession"] = ("YOUR CONNECTION", "ВАШЕ СОЕДИНЕНИЕ", "BAĞLANTINIZ"),
        ["LanguageHint"] = ("Choose the language that feels like home. Changes are saved automatically.", "Выберите удобный язык. Изменение сохраняется автоматически.", "Rahat olduğunuz dili seçin. Dəyişiklik avtomatik saxlanılır."),
        ["Preferences"] = ("Make it yours", "Как вам удобно", "Sizə uyğun"),
        ["Language"] = ("Language", "Язык", "Dil"),
        ["Tray"] = ("Minimize to system tray", "Сворачивать в системный трей", "Sistem treyinə yığ"),
        ["AutoStart"] = ("Open with Windows", "Открывать при запуске Windows", "Windows ilə aç"),
        ["Recovery"] = ("Reconnect after an interruption", "Переподключаться после сбоя", "Kəsintidən sonra yenidən qoşul"),
        ["Updates"] = ("Check for app updates on launch", "Проверять обновления при запуске", "Başlanğıcda tətbiq yeniləmələrini yoxla"),
        ["Save"] = ("Save settings", "Сохранить настройки", "Parametrləri saxla"),
        ["CheckUpdates"] = ("Check updates now", "Проверить обновления", "Yeniləmələri yoxla"),
        ["Privacy"] = ("No telemetry. Website checks run only when you ask. Optional update checks contact the app’s update service. All required components are included.", "Без телеметрии. Проверка сайтов выполняется только по вашему запросу. Добровольная проверка обновлений обращается к сервису обновления приложения. Все необходимые компоненты включены.", "Telemetriya yoxdur. Saytlar yalnız istəyinizlə yoxlanılır. Könüllü yeniləmə yoxlamaları tətbiqin yeniləmə xidmətinə müraciət edir. Bütün zəruri komponentlər daxildir."),
        ["AboutText"] = ("Northpass 0.7\nA simpler connection experience for Windows.", "Northpass 0.7\nПростой способ управлять соединением в Windows.", "Northpass 0.7\nWindows üçün daha sadə bağlantı təcrübəsi."),
        ["AvailabilityNote"] = ("Website access depends on your network. Northpass does not guarantee access to every website.", "Доступ к сайтам зависит от вашей сети. Northpass не гарантирует доступ к каждому сайту.", "Saytlara giriş şəbəkənizdən asılıdır. Northpass hər sayta girişi təmin etmir."),
        ["Show"] = ("Show Northpass", "Открыть Northpass", "Northpass-ı aç"),
        ["Exit"] = ("Exit", "Выход", "Çıxış"),
        ["Welcome"] = ("Everything you need is included.", "Всё необходимое уже включено.", "Lazım olan hər şey daxildir."),
        ["HomeNote"] = ("One click to get started. Northpass handles the rest.", "Одно нажатие для запуска. Остальное сделает Northpass.", "Başlamaq üçün bir klik. Qalanını Northpass həll edir."),
        ["ActiveNote"] = ("Connection started. Web access is checked separately below.", "Соединение запущено. Доступ к сайтам проверяется отдельно ниже.", "Bağlantı başladılıb. Saytlara giriş aşağıda ayrıca yoxlanılır."),
        ["Hero"] = ("Your connection.\nMade simple.", "Ваше соединение.\nВсё просто.", "Bağlantınız.\nSadə şəkildə."),
        ["Tagline"] = ("A quieter way to connect", "Подключение без лишних забот", "Rahat bağlantı"),
        ["AdvancedNote"] = ("For experienced users. Changes here can affect your connection. The included configuration is ready to use.", "Для опытных пользователей. Изменения могут повлиять на соединение. Встроенная конфигурация готова к использованию.", "Təcrübəli istifadəçilər üçün. Dəyişikliklər bağlantıya təsir edə bilər. Daxil edilmiş konfiqurasiya istifadəyə hazırdır."),
        ["LicensesTitle"] = ("Licenses & acknowledgements", "Лицензии и благодарности", "Lisenziyalar və təşəkkürlər"),
        ["ViewLicenses"] = ("View licenses", "Открыть лицензии", "Lisenziyalara bax"),
        ["ViewSources"] = ("Included source packages", "Включённые исходные коды", "Daxil edilmiş mənbə paketləri"),
        ["Continue"] = ("Continue", "Продолжить", "Davam et"),
        ["Cancel"] = ("Cancel", "Отмена", "Ləğv et"),
        ["Close"] = ("Close", "Закрыть", "Bağla"),
        ["Minimize"] = ("Minimize", "Свернуть", "Kiçilt"),
        ["Maximize"] = ("Maximize / restore", "Развернуть / восстановить", "Böyüt / bərpa et"),
        ["InstallationFailed"] = ("Northpass could not prepare its components. Try Repair installation in Settings. Details are available in Diagnostics.", "Не удалось подготовить компоненты. Попробуйте восстановить установку в настройках. Подробности — в диагностике.", "Northpass komponentləri hazırlaya bilmədi. Parametrlərdə quraşdırmanı bərpa edin. Təfərrüatlar Diaqnostikadadır."),
        ["ValidationFailed"] = ("The connection settings could not be used. Choose the included configuration in Advanced, or see Diagnostics for details.", "Не удалось применить настройки соединения. Выберите встроенную конфигурацию в дополнительных инструментах или откройте диагностику.", "Bağlantı parametrləri istifadə edilə bilmədi. Əlavə alətlərdə daxil edilmiş konfiqurasiyanı seçin və ya Diaqnostikaya baxın."),
        ["ConnectionFailed"] = ("Northpass could not start the connection. Try again or open Diagnostics for details.", "Не удалось запустить соединение. Повторите попытку или откройте диагностику.", "Northpass bağlantını başlada bilmədi. Yenidən cəhd edin və ya Diaqnostikanı açın."),
        ["NetworkBlocked"] = ("Windows could not initialize the network module. Restart your computer and try again. Keep Windows security enabled; see Diagnostics for details.", "Windows не удалось запустить сетевой модуль. Перезагрузите компьютер и повторите попытку. Не отключайте защиту Windows; подробности — в диагностике.", "Windows şəbəkə modulunu başlada bilmədi. Kompüteri yenidən başladıb cəhd edin. Windows təhlükəsizliyini aktiv saxlayın; təfərrüatlar Diaqnostikadadır."),
        ["ActionFailed"] = ("That action could not be completed. Open Diagnostics for details.", "Не удалось выполнить действие. Подробности — в диагностике.", "Əməliyyat tamamlana bilmədi. Təfərrüatlar üçün Diaqnostikanı açın."),
        ["SettingsSaved"] = ("Preferences saved.", "Настройки сохранены.", "Parametrlər saxlanıldı."),
        ["AlreadyOpen"] = ("Northpass is already open. Use its icon in the system tray.", "Northpass уже открыт. Используйте значок в системном трее.", "Northpass artıq açıqdır. Sistem treyindəki işarədən istifadə edin."),
        ["StartupFailed"] = ("Northpass could not open. Repair the application installation and try again.", "Не удалось открыть Northpass. Восстановите установку приложения и повторите попытку.", "Northpass açıla bilmədi. Tətbiqin quraşdırılmasını bərpa edib yenidən cəhd edin."),
        ["StopFailed"] = ("The connection could not be stopped. Northpass will stay open so you can try again. Details are in Diagnostics.", "Не удалось остановить соединение. Northpass останется открытым для повторной попытки. Подробности — в диагностике.", "Bağlantı dayandırıla bilmədi. Yenidən cəhd edə bilməniz üçün Northpass açıq qalacaq. Təfərrüatlar Diaqnostikadadır."),
        ["ReinstallRequired"] = ("Northpass installation is incomplete. Run the Northpass installer again. Details are in Diagnostics.", "Установка Northpass неполная. Запустите установщик Northpass ещё раз. Подробности — в диагностике.", "Northpass quraşdırılması natamamdır. Northpass quraşdırıcısını yenidən başladın. Təfərrüatlar Diaqnostikadadır."),
        ["PermissionDeclined"] = ("Permission to initialize the network module was declined. Click Connect to try again.", "Разрешение на запуск сетевого модуля отклонено. Нажмите «Подключить», чтобы повторить.", "Şəbəkə modulunu başlatmaq icazəsi rədd edildi. Yenidən cəhd etmək üçün Qoşul düyməsini basın."),
        ["AccessDenied"] = ("Windows could not access the required components. Contact your administrator; details are in Diagnostics.", "Windows не удалось получить доступ к нужным компонентам. Обратитесь к администратору; подробности — в диагностике.", "Windows lazımi komponentlərə giriş əldə edə bilmədi. Administratorla əlaqə saxlayın; təfərrüatlar Diaqnostikadadır."),
        ["EngineConflict"] = ("Another network module is already running. Close it using its own controls, then try again. Northpass will not stop other applications.", "Уже работает другой сетевой модуль. Закройте его через его собственные элементы управления и повторите попытку. Northpass не останавливает другие приложения.", "Başqa şəbəkə modulu artıq işləyir. Onu öz idarəetmə vasitələri ilə bağlayıb yenidən cəhd edin. Northpass başqa tətbiqləri dayandırmır."),
        ["BundledDefault"] = ("Included default", "Встроенный вариант", "Daxil edilmiş seçim"),
        ["DataLists"] = ("Data-only lists", "Списки данных", "Yalnız məlumat siyahıları"),
        ["DataListNote"] = ("Only UTF-8 .txt domain names or IP/CIDR addresses. Executables and scripts are rejected. Included lists remain unchanged. Select a list below, then save.", "Только домены или IP/CIDR в UTF-8 .txt. Исполняемые файлы и скрипты запрещены. Встроенные списки сохраняются. Выберите список и сохраните.", "Yalnız UTF-8 .txt domen adları və ya IP/CIDR ünvanları. İcra faylları və skriptlər qəbul edilmir. Daxil edilmiş siyahılar dəyişmir. Siyahını seçib saxlayın."),
        ["GeneralHosts"] = ("Additional domains", "Дополнительные домены", "Əlavə domenlər"),
        ["ExcludedHosts"] = ("Excluded domains", "Исключённые домены", "İstisna edilən domenlər"),
        ["ExcludedIps"] = ("Excluded IP addresses", "Исключённые IP-адреса", "İstisna edilən IP ünvanları"),
        ["AllIps"] = ("Custom IP set", "Пользовательский набор IP", "Fərdi IP dəsti"),
        ["GamePorts"] = ("Additional TCP / UDP ports", "Дополнительные порты TCP / UDP", "Əlavə TCP / UDP portları"),
        ["GamePortsNote"] = ("Default 12 preserves the upstream disabled game-filter setting. Enter decimal ports/ranges only. Reviewed strategy arguments cannot be edited.", "Значение 12 сохраняет отключённый игровой фильтр из исходного проекта. Только десятичные порты/диапазоны. Аргументы проверенных стратегий неизменяемы.", "Standart 12 ilkin layihədəki söndürülmüş oyun filtrini saxlayır. Yalnız onluq portlar/aralıqlar. Yoxlanmış strategiya arqumentləri dəyişdirilə bilməz."),
        ["SaveInputs"] = ("Save strategy inputs", "Сохранить параметры стратегии", "Strategiya məlumatlarını saxla"),
        ["GuidedTest"] = ("Test selected strategy", "Проверить выбранную стратегию", "Seçilmiş strategiyanı yoxla"),
        ["NextStrategy"] = ("Choose next strategy", "Выбрать следующую стратегию", "Növbəti strategiyanı seç"),
        ["Provider"] = ("Network / provider label (optional)", "Название сети / провайдера (необязательно)", "Şəbəkə / provayder adı (istəyə bağlı)"),
        ["StrategyTestConsent"] = ("Stop the current connection, start only the selected configuration, and check YouTube, Discord and Telegram? The test stops the connection afterwards. Results and logs are saved locally. It does not test video playback or voice.", "Остановить текущее соединение, запустить только выбранную конфигурацию и проверить YouTube, Discord и Telegram? После проверки соединение остановится. Результаты и журнал сохраняются локально. Воспроизведение видео и голос не проверяются.", "Cari bağlantı dayandırılsın, yalnız seçilmiş konfiqurasiya başlasın və YouTube, Discord və Telegram yoxlanılsın? Testdən sonra bağlantı dayandırılır. Nəticələr və jurnallar yerli saxlanılır. Video və səs yoxlanılmır."),
        ["ServiceChecks"] = ("Check services", "Проверить сервисы", "Xidmətləri yoxla"),
        ["ProbeScope"] = ("Website checks only. Video playback, login, gateway, QUIC, STUN and voice: not tested.", "Проверка только сайтов. Видео, вход, шлюз, QUIC, STUN и голос: не проверены.", "Yalnız sayt yoxlamaları. Video, giriş, keçid, QUIC, STUN və səs: yoxlanılmayıb."),
        ["Passed"] = ("Passed", "Успешно", "Uğurlu"),
        ["Failed"] = ("Failed", "Неудачно", "Uğursuz"),
        ["Unknown"] = ("Not tested", "Не проверено", "Yoxlanılmayıb"),
        ["ManualOutcomeConsent"] = ("Record your own observation for the last strategy test? This is a user report, separate from automated checks. Connect that strategy and verify real video playback or a two-way voice call first.", "Сохранить ваше наблюдение для последней проверки стратегии? Это сообщение пользователя, отдельно от автоматических проверок. Сначала подключите эту стратегию и проверьте воспроизведение видео или двусторонний голосовой звонок.", "Son strategiya testi üçün müşahidəniz qeydə alınsın? Bu, avtomatik yoxlamalardan ayrı istifadəçi hesabatıdır. Əvvəlcə həmin strategiya ilə qoşulub video və ya ikitərəfli səsli zəngi yoxlayın."),
        ["PlaybackPassed"] = ("Video worked (my report)", "Видео работает (мой отчёт)", "Video işlədi (hesabatım)"),
        ["PlaybackFailed"] = ("Video failed (my report)", "Видео не работает (мой отчёт)", "Video işləmədi (hesabatım)"),
        ["VoicePassed"] = ("Voice worked (my report)", "Голос работает (мой отчёт)", "Səs işlədi (hesabatım)"),
        ["VoiceFailed"] = ("Voice failed (my report)", "Голос не работает (мой отчёт)", "Səs işləmədi (hesabatım)"),
        ["Available"] = ("Available", "Доступно", "Əlçatandır"),
        ["Limited"] = ("Limited", "Ограничено", "Məhdud"),
        ["Unavailable"] = ("Unavailable", "Недоступно", "Əlçatan deyil"),
        ["WebCheck"] = ("Web access", "Доступ к сайту", "Sayta giriş"),
        ["DiagnosticsSummary"] = ("A quick look at your web access", "Быстрая проверка доступа к сайтам", "Saytlara girişin qısa yoxlaması"),
        ["CheckingServices"] = ("Checking your connection…", "Проверяем соединение…", "Bağlantınız yoxlanılır…"),
        ["DiagnosticsScope"] = ("These checks cover each service’s website. Video, calls and messaging need a separate real-world check.", "Проверяем сайты сервисов. Видео, звонки и сообщения требуют отдельной проверки в реальных условиях.", "Bu yoxlamalar xidmətlərin saytlarını əhatə edir. Video, zənglər və mesajlaşma ayrıca real yoxlama tələb edir."),
        ["CheckServices"] = ("Check again", "Проверить ещё раз", "Yenidən yoxla"),
        ["StrategyHint"] = ("Disconnect before choosing a different strategy. Results depend on your network.", "Отключитесь перед выбором другой стратегии. Результат зависит от вашей сети.", "Başqa strategiyanı seçməzdən əvvəl ayrılın. Nəticələr şəbəkənizdən asılıdır."),
        ["Strategy_general"] = ("Balanced", "Сбалансированная", "Balanslı"),
        ["Strategy_alt"] = ("Alternate I", "Альтернатива I", "Alternativ I"),
        ["Strategy_alt2"] = ("Alternate II", "Альтернатива II", "Alternativ II"),
        ["Strategy_simple-fake"] = ("Simple", "Простая", "Sadə"),
        ["Strategy_fake-tls-auto"] = ("Adaptive", "Адаптивная", "Uyğunlaşan"),
        ["Custom"] = ("Custom", "Своя", "Fərdi"),
        ["AboutProduct"] = ("A calmer connection experience. Reviewed components, thoughtful controls, and a clear view of your network.", "Спокойный опыт подключения. Проверенные компоненты, удобное управление и понятная картина состояния сети.", "Daha rahat bağlantı təcrübəsi. Yoxlanmış komponentlər, sadə idarəetmə və şəbəkənizin aydın görünüşü."),
        ["SupportTitle"] = ("Help with your connection", "Помощь с соединением", "Bağlantı üçün kömək"),
        ["SupportInfo"] = ("Run the built-in checks and export a diagnostic report if you need support. Review the report before sharing it.", "Запустите встроенные проверки и экспортируйте отчёт для поддержки. Просмотрите отчёт перед отправкой.", "Daxili yoxlamaları başladın və kömək üçün diaqnostika hesabatını ixrac edin. Paylaşmazdan əvvəl hesabatı nəzərdən keçirin."),
        ["OpenDiagnostics"] = ("Open diagnostics", "Открыть диагностику", "Diaqnostikanı aç"),
        ["UpdateInfo"] = ("Everything needed is included. Updates are optional; checks never install anything automatically.", "Всё необходимое включено. Обновления добровольны; проверка ничего не устанавливает автоматически.", "Lazım olan hər şey daxildir. Yeniləmələr istəyə bağlıdır; yoxlama heç nəyi avtomatik quraşdırmır."),
        ["UpdateAvailable"] = ("A Northpass update is available. Contact your trusted distributor for the new installer.", "Доступно обновление Northpass. Получите новый установщик у доверенного поставщика.", "Northpass yeniləməsi mövcuddur. Yeni quraşdırıcını etibarlı mənbədən əldə edin."),
        ["UpToDate"] = ("Your Northpass version is up to date.", "Установлена актуальная версия Northpass.", "Northpass versiyanız yenidir."),
        ["NoPublishedUpdate"] = ("No Northpass update has been published yet.", "Обновление Northpass пока не опубликовано.", "Northpass yeniləməsi hələ dərc edilməyib."),
        ["Legal"] = ("Licenses & legal", "Лицензии и правовая информация", "Lisenziyalar və hüquqi məlumat"),
        ["LegalInfo"] = ("Third-party attribution, full licenses and corresponding source packages.", "Авторство сторонних компонентов, полные лицензии и соответствующие исходные коды.", "Üçüncü tərəf müəllifliyi, tam lisenziyalar və müvafiq mənbə paketləri."),
        ["TechnicalDetails"] = ("Details & local logs", "Подробности и локальный журнал", "Təfərrüatlar və yerli jurnallar"),
        ["AutomaticPrivacy"] = ("No telemetry. Built-in website checks run at launch and after connection changes; Check again refreshes them. No account credentials are sent. Update checks are optional.", "Без телеметрии. Сайты проверяются при запуске и после изменения соединения; «Проверить ещё раз» повторяет проверку. Данные аккаунтов не отправляются. Проверка обновлений добровольна.", "Telemetriya yoxdur. Saytlar başlanğıcda və bağlantı dəyişdikdən sonra yoxlanılır; «Yenidən yoxla» onları yeniləyir. Hesab məlumatları göndərilmir. Yeniləmə yoxlamaları istəyə bağlıdır."),
    };
}
