namespace Northpass.Engine.Zapret2;

// Exact option names/arity reviewed in nfq2/nfqws.c at
// a1adf7b868e65c8a77aab608c8bbd9ec8b30a256. No getopt abbreviation is accepted.
internal static class Zapret2Options
{
    public static readonly IReadOnlyDictionary<string, string> Known = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["--debug"] = "optional_argument",
        ["--dry-run"] = "no_argument",
        ["--intercept"] = "optional_argument",
        ["--fuzz"] = "required_argument",
        ["--version"] = "no_argument",
        ["--comment"] = "optional_argument",
        ["--daemon"] = "no_argument",
        ["--chdir"] = "optional_argument",
        ["--pidfile"] = "required_argument",
        ["--ctrack-timeouts"] = "required_argument",
        ["--ctrack-disable"] = "optional_argument",
        ["--payload-disable"] = "optional_argument",
        ["--server"] = "optional_argument",
        ["--ipcache-lifetime"] = "required_argument",
        ["--ipcache-hostname"] = "optional_argument",
        ["--reasm-disable"] = "optional_argument",
        ["--writable"] = "optional_argument",
        ["--blob"] = "required_argument",
        ["--lua-init"] = "required_argument",
        ["--lua-gc"] = "required_argument",
        ["--hostlist"] = "required_argument",
        ["--hostlist-domains"] = "required_argument",
        ["--hostlist-exclude"] = "required_argument",
        ["--hostlist-exclude-domains"] = "required_argument",
        ["--hostlist-auto"] = "required_argument",
        ["--hostlist-auto-fail-threshold"] = "required_argument",
        ["--hostlist-auto-fail-time"] = "required_argument",
        ["--hostlist-auto-retrans-threshold"] = "required_argument",
        ["--hostlist-auto-retrans-maxseq"] = "required_argument",
        ["--hostlist-auto-retrans-reset"] = "optional_argument",
        ["--hostlist-auto-incoming-maxseq"] = "required_argument",
        ["--hostlist-auto-udp-in"] = "required_argument",
        ["--hostlist-auto-udp-out"] = "required_argument",
        ["--hostlist-auto-debug"] = "required_argument",
        ["--new"] = "optional_argument",
        ["--skip"] = "no_argument",
        ["--name"] = "required_argument",
        ["--template"] = "optional_argument",
        ["--import"] = "required_argument",
        ["--cookie"] = "required_argument",
        ["--filter-l3"] = "required_argument",
        ["--filter-tcp"] = "required_argument",
        ["--filter-udp"] = "required_argument",
        ["--filter-icmp"] = "required_argument",
        ["--filter-ipp"] = "required_argument",
        ["--filter-l7"] = "required_argument",
        ["--filter-ssid"] = "required_argument",
        ["--filter-ssid-neg"] = "optional_argument",
        ["--ipset"] = "required_argument",
        ["--ipset-ip"] = "required_argument",
        ["--ipset-exclude"] = "required_argument",
        ["--ipset-exclude-ip"] = "required_argument",
        ["--payload"] = "required_argument",
        ["--in-range"] = "required_argument",
        ["--out-range"] = "required_argument",
        ["--lua-desync"] = "required_argument",
        ["--wf-iface"] = "required_argument",
        ["--wf-l3"] = "required_argument",
        ["--wf-tcp-in"] = "required_argument",
        ["--wf-tcp-out"] = "required_argument",
        ["--wf-udp-in"] = "required_argument",
        ["--wf-udp-out"] = "required_argument",
        ["--wf-tcp-empty"] = "optional_argument",
        ["--wf-icmp-in"] = "required_argument",
        ["--wf-icmp-out"] = "required_argument",
        ["--wf-ipp-in"] = "required_argument",
        ["--wf-ipp-out"] = "required_argument",
        ["--wf-raw"] = "required_argument",
        ["--wf-raw-part"] = "required_argument",
        ["--wf-raw-filter"] = "required_argument",
        ["--wf-filter-lan"] = "required_argument",
        ["--wf-filter-loopback"] = "required_argument",
        ["--wf-save"] = "required_argument",
        ["--wf-dup-check"] = "optional_argument",
        ["--ssid-filter"] = "required_argument",
        ["--ssid-filter-neg"] = "optional_argument",
        ["--nlm-filter"] = "required_argument",
        ["--nlm-filter-neg"] = "optional_argument",
        ["--nlm-list"] = "optional_argument",
    };
}
